add_subdirectory(calculator)
add_subdirectory(libA_example)
add_subdirectory(libB_example)
add_subdirectory(crash_diagnostic)
add_subdirectory(registry_demo)
add_subdirectory(service_locator_demo)
add_subdirectory(versioned_calculator)
add_subdirectory(hot_reload_demo)
add_subdirectory(dynamic_plugin_demo)
add_subdirectory(lifecycle_demo)
add_subdirectory(managed_demo)
add_subdirectory(dotnet_bridge)
add_subdirectory(features_demo)
add_subdirectory(diagnostic_dump)
add_subdirectory(config_hot_reload)
add_subdirectory(metrics_observer)
add_subdirectory(dot_graph)
add_subdirectory(capability_negotiation)
